plugins {
    id 'com.android.application'
}

android {
    configurations.all {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    }
    namespace 'com.example.smartcropapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.smartcropapp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    signingConfigs {
        if (file("${rootDir}/debug.keystore").exists()) {
            debugConfig {
                storeFile file("${rootDir}/debug.keystore")
                storePassword "android"
                keyAlias "androiddebugkey"
                keyPassword "android"
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debugConfig
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            if (file("${rootDir}/debug.keystore").exists()) {
                signingConfig signingConfigs.debugConfig
            }
            minifyEnabled false
            shrinkResources false
        }
    }
    externalNativeBuild {
        cmake { path file("src/main/cpp/CMakeLists.txt") }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.mlkit:pose-detection:18.0.0-beta5'
    testImplementation 'junit:junit:4.13.2'
}
